# Settings

* `options()` set and query global options which affect the way in which R computes and displays its results
* `Sys.setenv()` set or unset environment variables
* `Sys.setlocale()` set locale
* `sessionInfo()` print information about current R session
* `par()` graphical parameters
* `palette()` Current color palette


```{r, eval=FALSE}
options(digits = 3)          # by default 7 digits are printed
```


## Error language

```{r, error=TRUE, collapse=TRUE}
## default error language  operating system 
Sys.getenv("LANG")
not_existing_object

## error language on German (Seems NOT to work in R Markdown)
Sys.setenv(LANG="de")
not_existing_object

## error language on English
Sys.setenv(LANG="en")
not_existing_object
```


## Local
```{r, eval=FALSE}
x <- strptime(x = "10.05.1993", format = "%d.%m.%Y")

## default local of operating system
Sys.getlocale("LC_TIME")
## [1] "C"
format(x = x, "%B")
## [1] "May"

## local German_Switzerland
if(.Platform$OS.type == "unix"){
  Sys.setlocale("LC_TIME", "de_CH.UTF-8")
} else if(.Platform$OS.type == "windows"){
  Sys.setlocale("LC_TIME", "German")
}
format(x = x, "%B")
## [1] "Mai"

## local English
Sys.setlocale("LC_TIME", "C")
format(x = x, "%B")
## [1] "May"
```

