# Bookdown

## Configuration

Some options are passed to

1) `bookdown::render()`
1) kniter
2) pandoc


Where to define configuration (see also [here](https://stackoverflow.com/questions/51424537/whats-the-difference-between-bookdown-yml-output-yml-and-yaml-header-of))

1) `_bookdown.yml`
2) `_output.yml`
3) yaml header of first document (index)


Example with all possible default options

### `_bookdown.yml`
```
book_filename: "myBookname"
delete_merged_file: true
language:
  ui:
    chapter_name: "Chapter "
chapter_name: "Chapter "
repo: https://github.com/seankross/bookdown-start
output_dir: docs
rmd_files: ["index.Rmd", "01-Introduction.Rmd", "02-Diving-In.Rmd"]
clean: [packages.bib, bookdown.bbl]
new_session: yes
```

Here: add explanation to each option


### `_output.yml`

```
bookdown::gitbook:
  css: style.css
  split_by: chapter
  config:
    toc:
      collapse: subsection
      before: |
        <li><a href="./">A Minimal Bookdown Book</a></li>
      after: |
        <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
bookdown::epub_book:
  stylesheet: style.css
```



### yaml header

```
---
title: "A Minimal Bookdown Book"
author: "Sean Kross"
date: "2016-12-02"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: seankross/bookdown-start
url: 'http\://seankross.com/bookdown-start/'
description: "Everything you need (and nothing more) to start a bookdown book."
---
```


## Create new project

1. Open template of RStudio
2. Connect with GitHub repository and push
3. github.com/retodomax/projectname
  a. go to Settings
  b. at GitHub Pages set source to docs folder
  c. Don't worry if page does not immideatly appear on link (takes long time to be built)
4. Make a figures folder containing a png and an ico file (transfere png to ico at some png-to-ico transformation website)
5. Set `_bookdown.yml`, `_output.yml` and yaml header with the options you whish.
6. Create content, build and push
