# Latex

## Symbols

[List of mathematical symbols](https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols)


<table class = "deftab">
  <tr>
    <td>**Space**</td>
    <td> </td>
  </tr>
  <tr>
    <td>space</td>
    <td>`\hspace{35pt}`</td>
  </tr>
  <tr>
    <td>space</td>
    <td>`\qquad`</td>
  </tr>
  <tr>
    <td>big space</td>
    <td>`\;`</td>
  </tr>
  <tr>
    <td>medium space</td>
    <td>`\:`</td>
  </tr>
  <tr>
    <td>small space</td>
    <td>`\,`</td>
  </tr>
  <tr>
    <td>negative space</td>
    <td>`\!`</td>
  </tr>
  <tr>
    <td>**Math**</td>
    <td> </td>
  </tr>
  <tr>
    <td>$\approx$</td>
    <td>`\approx`</td>
  </tr>
  <tr>
    <td>$\neq$</td>
    <td>`\neq`</td>
  </tr>
  <tr>
    <td>$\leq$</td>
    <td>`\leq`</td>
  </tr>
  <tr>
    <td>$\sim$</td>
    <td>`\sim`</td>
  </tr>
  <tr>
    <td>$\in$</td>
    <td>`\in`</td>
  </tr>
  <tr>
    <td>$\Rightarrow$</td>
    <td>`\Rightarrow`</td>
  </tr>
  <tr>
    <td>$\mid$</td>
    <td>`\mid`</td>
  </tr>
  <tr>
    <td>$\times$</td>
    <td>`\times`</td>
  </tr>
  <tr>
    <td>$\otimes$</td>
    <td>`\otimes`</td>
  </tr>
  <tr>
    <td>$\partial$</td>
    <td>`\partial`</td>
  </tr>
  <tr>
    <td>$\infty$</td>
    <td>`\infty`</td>
  </tr>
  <tr>
    <td>$\infty$</td>
    <td>`\infty`</td>
  </tr>
  <tr>
    <td>$\mathbb{R}$</td>
    <td>`\mathbb{R}`</td>
  </tr>
    <tr>
    <td>$\underbrace{\cdots}_{\cdots}$</td>
    <td>`\underbrace{\cdots}_{\cdots}`</td>
  </tr>
  <tr>
    <td>$\binom{n}{k}$</td>
    <td>`\binom{n}{k}`</td>
  </tr>
</table>

## Important

```{block2, type='rmdcaution'}
A dot which is not used as the end of a scentence has to be followed by a backslash (/). Otherwise there is too much space afterwards. Important for abbriviations like e.g., i.e., etc., et al., ...
```


## Reto Math

```{block2, type='rmdcaution'}
These are only working if the output is a pdf and the RetoMath.sty preamble is included
```

<table class = "deftab">
  <tr>
    <td>bold math</td>
    <td>`\bm`</td>
  </tr>
  <tr>
    <td>inverse</td>
    <td>`\inv`</td>
  </tr>
  <tr>
    <td>transpose</td>
    <td>`\tr`</td>
  </tr>
</table>

## SfS

```{block2, type='rmdcaution'}
These are only working if the output is a pdf and the RetoMath.sty preamble is included
```

<table class = "deftab">
  <tr>
    <td>R</td>
    <td>`\Rp`</td>
  </tr>
  <tr>
    <td>$E[\dots]$</td>
    <td>`\ERW{}`</td>
  </tr>
  <tr>
    <td>$\text{Var()}$</td>
    <td>`\VAR{}`</td>
  </tr>
  <tr>
    <td>$\hat{\text{Var}}()$</td>
    <td>`VARH{}`</td>
  </tr>
  <tr>
    <td>$\text{Cov()}$</td>
    <td>`\COV{}`</td>
  </tr>
  <tr>
    <td>$\hat{\text{Cov}}()$</td>
    <td>`COVH{}`</td>
  </tr>
  <tr>
    <td>$\text{P}[X = c]$</td>
    <td>`\PR{}`</td>
  </tr>
  <tr>
    <td>$\text{N}()$</td>
    <td>`\Normal{}`</td>
  </tr>
  <tr>
    <td>$\text{N}_n()$</td>
    <td>`\Normali{n}{}`</td>
  </tr>
  <tr>
    <td>$\text{B}()$</td>
    <td>`\Binomial{}`</td>
  </tr>
  <tr>
    <td>$\text{Bernoulli}()$</td>
    <td>`\Bernoulli{}`</td>
  </tr>
  <tr>
    <td>$\text{Exp}()$</td>
    <td>`\Exponential{}`</td>
  </tr>
  <tr>
    <td>$\text{Pois}()$</td>
    <td>`\Poisson{}`</td>
  </tr>
</table>

| Command                | Result                  | Command                    | Result                      | Command                | Result                  |
|------------------------|-------------------------|----------------------------|-----------------------------|------------------------|-------------------------|
| `\ERW{X}`              | $\ERW{X}$               | `\ERWi{X}`                 | $\ERWi{n}{X}$               | `\ERWSymbol`           | $\ERWSymbol$            |
| `\VAR{X}`              | $\VAR{X}$               | `\VARi{n}{X}`              | $\VARi{n}{X}$               | `\VARSymbol`           | $\VAR{X}$               |
| `\VARH{X}`             | $\VARH{X}$              | `\VARHi{n}{X}`             | $\VARHi{n}{X}$              | `\wh\VARSymbol`        | $\wh\VARSymbol$         |
| `\COV{X,Y}`            | $\COV{X,Y}$             | `\COVi{n}{X,Y}`            | $\COVi{n}{X,Y}$             | `\COVSymbol`           | $\COVSymbol$            |
| `\COVH{X,Y}`           | $\COVH{X,Y}$            | `\COVHi{n}{X,Y}`           | $\COVHi{n}{X,Y}$            | `\wh\COVSymbol`        | $\wh\COVSymbol$         |
| `\COR{X,Y}`            | $\COR{X,Y}$             | `\CORi{n}{X,Y}`            | $\CORi{n}{X,Y}$             | `\CORSymbol`           | $\CORSymbol$            |
| `\CORH{X,Y}`           | $\CORH{X,Y}$            | `\CORHi{n}{X,Y}`           | $\CORHi{n}{X,Y}$            | `\wh\CORSymbol`        | $\wh\CORSymbol$         |
| `\PR{X = c}`           | $\PR{X = c}$            | `\PRi{n}{X = c}`           | $\PRi{n}{X = c}$            | `\PRSymbol`            | $\PRSymbol$             |
| `\Normal{\mu, 1}`      | $\Normal{\mu, 1}$       | `\Normali{n}{\mu, 1}`      | $\Normali{n}{\mu, 1}$       | `\NormalSymbol`        | $\NormalSymbol$         |
| `\Binomial{n,p}`       | $\Binomial{n,p}$        | `\Binomiali{n}{n,p}`       | $\Binomiali{n}{n,p}$        | `\BinomialSymbol`      | $\BinomialSymbol$       |
| `\Bernoulli{p}`        | $\Bernoulli{p}$         | `\Bernoullii{n}{p}`        | $\Bernoullii{n}{p}$         | `\BernoulliSymbol`     | $\BernoulliSymbol$      |
| `\Exponential{\lambda}`| $\Exponential{\lambda}$ | `\Exponentiali{n}{\lambda}`| $\Exponentiali{n}{\lambda}$ | `\ExponentialSymbol`   | $\ExponentialSymbol$    |
| `\Poisson{\lambda}`    | $\Poisson{\lambda}$     | `\Poissoni{n}{\lambda}`    | $\Poissoni{n}{\lambda}$     | `\PoissonSymbol`       | $\PoissonSymbol$        |



## Constructs

<table class = "deftab">
  <tr>
    <td>$\begin{pmatrix} b_1 \\ \vdots \\ b_n \end{pmatrix}$</td>
    <td>`\begin{pmatrix} b_1 \\ \vdots \\ b_n \end{pmatrix}`</td>
  </tr>
</table>

## Text format

Colored text

`\textcolor{red}{...text...}`

## Math environments

Reto Math supports Theorems, Definitions, Results, Proofs and Examples. Definitions are followed by a black diamond ($\blacklozenge$), Proofs by an open square ($\square$) and examples by a filled square($\blacksquare$).

Example

```latex
\begin{example}
  This is an example
\end{example}
```

If math environment ends with display (equation block) add `\qedhere` to end of equation such that symbol is on same line as the equation and no page break can happen between end of equation and symbol.

```latex
\begin{example}
  This is an example
  \begin{equation*}
    x = 1+2 \qedhere
  \end{equation*}
\end{example}
```

Detailed information [here](https://tex.stackexchange.com/questions/16453/denoting-the-end-of-example-remark/32394#32394)

Consider replacing the current solution with package `ntheorem` (reasons outlined [here](https://tex.stackexchange.com/questions/232438/using-qedhere-automatically-in-every-proof). However, there are also arguments against it [here](https://tex.stackexchange.com/questions/5599/theorem-packages-which-to-use-which-conflict))
